### ISSUE TITLE
Home Page CSS

### ISSUE THREAD

**Issue by eal001** [cse110-fall22-group12/cse110-fall22-group12#14]
- [x] Style The HTML like the Figma Design
- [x] Make sure it is mobile responsive
- [x] Review by Lyu

**Comment by eal001** [comment]
Figma Link: https://www.figma.com/file/1adnoZuKp08lEbgpTtvXdT/Cooking-App%3A-High-Fidelity-Design
See Home Page Desktop and Mobile Page Desktop

**Comment by KelinLyu** [comment]
I removed the unnecessary empty lines following the rules we established.
