### ISSUE TITLE
Edit/Add Page JavaScript

### ISSUE THREAD

**Issue by eal001** [cse110-fall22-group12/cse110-fall22-group12#19]
This JavaScript page should handle two separate cases, the one where we came to this page from HOME, and this page from VIEW...

- [x] BOTH cases should check if recipe name field is blank
  - [x] We don't allow the user to save information if the recipe name field is blank
  - [x] Give user an alert popup if the recipe field is empty

If "current recipe" exists then this page is the EDIT page:
- [x] Fill in the (ingredient, steps, notes, text boxes) with the "current recipe" data
- [x] Header Back button should go back to the VIEW page
- [x] Header add button should save info then go back to the VIEW page 

If "current recipe" doesn't exist then this page is the ADD page:
- [x] All text areas should be blank
- [x] Header Back goes to the HOME page
- [x] Header Save should save our new recipe and go back to the HOME page

- [x] Review by Zheyuan

**Comment by l2lee** [comment]
@KelinLyu @sswwpp judging based on https://cse110-fall22-group12.github.io/cse110-fall22-group12/components/index.html which is the latest version of team-dev branch, the check button isn’t actually working when saving in the edit and add page
