### ISSUE TITLE
Edit page empty recipe alert

### ISSUE THREAD

**Issue by Alex-Wang1** [cse110-fall22-group12/cse110-fall22-group12#52]
- [x] Now I can add empty recipes to home page, show pop up alert when the recipe name is empty

**Comment by Alex-Wang1** [comment]
![Image](https://user-images.githubusercontent.com/96413681/203666189-76207d84-1ae3-4c81-be5a-cffa8f49b42e.png)

**Comment by KelinLyu** [comment]
We cannot complete this until we have the function for the alert box, so that when the user wants to set an empty name, the alert box appears.

**Comment by TomlandHilarious** [comment]
This issue is fixed by the view page development team.
