### ISSUE TITLE
Create prettier config for the group

### ISSUE THREAD

**Issue by Alex-Wang1** [cse110-fall22-group12/cse110-fall22-group12#55]
- [x] Create a prettier config to help checking the coding format

**Comment by Alex-Wang1** [comment]
Refer to the link here: https://docs.google.com/document/d/1VBHeNCjW_qJrUtGQUTX3oEH_4rscSO43uN4_CTGrFbw/edit?usp=sharing

**Comment by sswwpp** [comment]
Created and finalized v.1. Waiting for review.
