### ISSUE TITLE
Finish the high fidelity design UI

### ISSUE THREAD

**Issue by Alex-Wang1** [cse110-fall22-group12/cse110-fall22-group12#8]
- [x] Finalize the design of the fundamental components
- [x] Finalize the color
- [x] Finalize the font

**Comment by Alex-Wang1** [comment]
- [ ] Finalize the design of the fundamental components
- [ ] Finalize the color
- [ ] Finalize the font

**Comment by eal001** [comment]
Design Doc has been finalized here: https://www.figma.com/file/1adnoZuKp08lEbgpTtvXdT/Cooking-App%3A-High-Fidelity-Design?node-id=0%3A1
