### ISSUE TITLE
Home page HTML

### ISSUE THREAD

**Issue by Alex-Wang1** [cse110-fall22-group12/cse110-fall22-group12#9]
- [x] Write skeleton code for the home page, like designing a PA for yourself 
- [x] Include header
- [x] Write comments
- [x] Possibly add a 'component' for the recipe card
- [x] Review by Lyu

**Comment by Alex-Wang1** [comment]
Figma link: https://www.figma.com/file/1adnoZuKp08lEbgpTtvXdT/Cooking-App%3A-High-Fidelity-Design?node-id=0%3A1


![Image](https://user-images.githubusercontent.com/96413681/201499609-b9ea322c-54d8-4756-b4ef-58dc7859a605.png)

[Please ignore the comments tag on the picture, that's not part of the project]

**Comment by KelinLyu** [comment]
I reindented the page and modified the documentations based on the rules we established.
